/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const JobId = IDL.Text;
export const Config = IDL.Record({
  'modelVersion' : IDL.Text,
  'modelId' : IDL.Text,
});
export const JobStatus = IDL.Variant({
  'completed' : IDL.Null,
  'queued' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Job = IDL.Record({
  'id' : JobId,
  'status' : JobStatus,
  'inputImageUrl' : IDL.Text,
  'inputImage' : ExternalBlob,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'replicateId' : IDL.Opt(IDL.Text),
  'motionIntensity' : IDL.Nat,
  'updatedAt' : Timestamp,
  'outputVideoUrl' : IDL.Opt(IDL.Text),
  'errorMsg' : IDL.Opt(IDL.Text),
});
export const JobListResult = IDL.Record({
  'total' : IDL.Nat,
  'jobs' : IDL.Vec(Job),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createJob' : IDL.Func([ExternalBlob, IDL.Text, IDL.Nat], [JobId], []),
  'deleteJob' : IDL.Func([JobId], [IDL.Bool], []),
  'getConfig' : IDL.Func([], [Config], ['query']),
  'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
  'listJobs' : IDL.Func(
      [IDL.Opt(JobStatus), IDL.Nat, IDL.Nat],
      [JobListResult],
      ['query'],
    ),
  'pollReplicateJob' : IDL.Func([JobId], [], []),
  'setReplicateApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateJobStatus' : IDL.Func(
      [JobId, JobStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const JobId = IDL.Text;
  const Config = IDL.Record({
    'modelVersion' : IDL.Text,
    'modelId' : IDL.Text,
  });
  const JobStatus = IDL.Variant({
    'completed' : IDL.Null,
    'queued' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Job = IDL.Record({
    'id' : JobId,
    'status' : JobStatus,
    'inputImageUrl' : IDL.Text,
    'inputImage' : ExternalBlob,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'replicateId' : IDL.Opt(IDL.Text),
    'motionIntensity' : IDL.Nat,
    'updatedAt' : Timestamp,
    'outputVideoUrl' : IDL.Opt(IDL.Text),
    'errorMsg' : IDL.Opt(IDL.Text),
  });
  const JobListResult = IDL.Record({
    'total' : IDL.Nat,
    'jobs' : IDL.Vec(Job),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createJob' : IDL.Func([ExternalBlob, IDL.Text, IDL.Nat], [JobId], []),
    'deleteJob' : IDL.Func([JobId], [IDL.Bool], []),
    'getConfig' : IDL.Func([], [Config], ['query']),
    'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
    'listJobs' : IDL.Func(
        [IDL.Opt(JobStatus), IDL.Nat, IDL.Nat],
        [JobListResult],
        ['query'],
      ),
    'pollReplicateJob' : IDL.Func([JobId], [], []),
    'setReplicateApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateJobStatus' : IDL.Func(
        [JobId, JobStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };